eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:Password%231@udemy-cluster.v69bwyk.mongodb.net/?retryWrites=true&w=majority # mongodb://localhost:27017/orderdb
      host: udemy-cluster.v69bwyk.mongodb.net
      port: 27017
      database: udemy_fs_orderdb
      repositories:
        enabled: true
